name: Auth CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test:cov
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            dist
            coverage
  code-quality:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=nerd
            -Dsonar.projectKey=auth_microservices
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.inclusions=src/**/*.ts
            -Dsonar.exclusions=src/**/test/**.ts,src/*.ts,src/migration/*.ts,src/shared/db/*.ts
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
